From node:18.12.1
RUN mkdir '/WebReportJsoftF'
WORKDIR '/WebReportJsoftF'

COPY . /WebReportJsoft
COPY package.json .
RUN npm install

COPY . .

RUN npm ci 
ENV NODE_ENV production
RUN npm run build
EXPOSE 7578
CMD [ "npx", "serve", "build" ]