From node:18.12.1
RUN mkdir '/WebReportJsoftF'
WORKDIR '/WebReportJsoftF'

COPY . /WebReportJsoft
COPY package.json .
RUN npm install

COPY . ./


RUN npm run build
ENV NODE_ENV production
EXPOSE 7578
CMD [ "npx", "serve", "build" ]