From node:18.12.1
RUN mkdir '/WebReportJsoftF'
WORKDIR '/WebReportJsoftF'

COPY . /WebReportJsoft
COPY package.json .
RUN npm install
COPY . .
EXPOSE 7578
CMD [ "npm","run","build" ]
CMD [ "serve","-s","build" ]